refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      kind: pattern
      pattern: "{d(%Y-%m-%d %H:%M:%S %Z)} {T} {M} {h({l})} - {m}{n}"
    target: stdout

  file:
    kind: rolling_file
    path: "logs/app.log"
    append: true
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S %Z)} {T} {M} {l} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 100 mb
      roller:
        kind: fixed_window
        pattern: "logs/app.log.{}"
        count: 3
        base: 1

root:
  level: debug
  appenders:
    - stdout
    - file

loggers:
  actix_web:
    level: info
  tokio:
    level: warn
  rustls:
    level: error
