refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {T} {M} {l} - {m}{n}"
    filters:
      - kind: threshold
        level: info

  file:
    kind: rolling_file
    path: "logs/app.log"
    append: true
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {T} {M} {l} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 100 mb
      roller:
        kind: fixed_window
        pattern: "logs/app.log.{}"
        count: 3
        base: 1

root:
  level: info
  appenders:
    - stdout
    - file

loggers:
  actix_web:
    level: info
  tokio:
    level: warn
  rustls:
    level: error
